server:
  port: 8080
spring:
  application:
    name: gym
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/gym?createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
