spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym?createIfDatabaseDoesNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
server:
  port: 8082