spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telecom_user_service?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: user-service

server:
  port: 8081


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
