spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ #database name
    username: #username
    password: #password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
