spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TradeMaster?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
   # root: DEBUG
   
  # Set the root logging level to DEBUG
   com:
     cn:
       trademaster: DEBUG
  file:
    name: trade-master-debug.log  # Specify the log file name
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
