spring:
  datasource:
    url: jdbc:h2:mem:PaymentDB
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
    port : 9000
server:
  port: 8087