  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/edtech_course_service?useSSL=false
      username: root
      password: 1234
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: update
    application:
      name: course-service
  server:
    port: 8081